version: "3.2"

services:
  # App
  app:
    container_name: StegWare-Backend_APP
    build: ./app
    restart: always
    env_file: .env
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    expose:
      - "${SERVER_PORT}"
    depends_on:
      - mongo
    links:
      - mongo

  # MongoDB
  mongo:
    container_name: StegWare-Backend_DB
    image: mongo:latest
    restart: always
    env_file: .env
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - './app/database/dump:/docker-entrypoint-initdb.d'

volumes:
  mongo:
    driver: local
